# Generated by Django 4.1.7 on 2023-03-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WH3Lord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('faction', models.TextField(max_length=100)),
                ('summary_of_changes', models.TextField(max_length=500)),
            ],
        ),
    ]
