# Generated by Django 4.1.7 on 2023-03-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_main', '0003_wh3lord_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='wh3lord',
            name='changes_picture',
            field=models.ImageField(default='', upload_to='C:\\dev\\django\\site_\\static\\wh3_lords_pictures'),
        ),
        migrations.AlterField(
            model_name='wh3lord',
            name='icon',
            field=models.ImageField(default='', upload_to='C:\\dev\\django\\site_\\static\\wh3_lords_icons'),
        ),
    ]
