# Generated by Django 4.1.7 on 2023-03-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_main', '0004_wh3lord_changes_picture_alter_wh3lord_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='wh3lord',
            name='campaign_review',
            field=models.TextField(default='NotEntered'),
        ),
        migrations.AddField(
            model_name='wh3lord',
            name='title',
            field=models.TextField(default='NotEntered', max_length=300),
        ),
    ]
