# Generated by Django 4.1.7 on 2023-03-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_main', '0005_wh3lord_campaign_review_wh3lord_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wh3lord',
            name='changes_picture',
            field=models.ImageField(default='', upload_to='wh3_lords_pictures'),
        ),
        migrations.AlterField(
            model_name='wh3lord',
            name='icon',
            field=models.ImageField(default='', upload_to='wh3_lords_icons'),
        ),
    ]
